<?xml version="1.0" encoding="utf-8"?><Database Name="Quickbooks" Class="QuickBooksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.8.0.200;Initial Catalog=Quickbooks;Persist Security Info=True;User ID=kburtoft" SettingsObjectName="QuickbooksWebService.DomainModel.Properties.Settings" SettingsPropertyName="QuickbooksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContentEditsClientID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OwnerIDGuid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QwcFile" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FileIDGuid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QbType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RequiresInventoryUpdate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SalesTaxReference" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingReference" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceClassRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceTemplateRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailRecipient" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsContentEditsShop" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RequiresTaxCodeUpdate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RequiresInvoiceTemplateUpdate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RequiresInvoiceClassUpdate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiscountRef" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Client_FailedOrder" Member="FailedOrders" ThisKey="ContentEditsClientID" OtherKey="ClientID" Type="FailedOrder" />
      <Association Name="Client_InventoryLink" Member="InventoryLinks" ThisKey="ContentEditsClientID" OtherKey="ClientID" Type="InventoryLink" />
      <Association Name="Client_Order" Member="Orders" ThisKey="ContentEditsClientID" OtherKey="ClientID" Type="Order" />
      <Association Name="Client_ResponseXML" Member="ResponseXMLs" ThisKey="ContentEditsClientID" OtherKey="ClientID" Type="ResponseXML" />
      <Association Name="Client_SalesTaxCode" Member="SalesTaxCodes" ThisKey="ContentEditsClientID" OtherKey="ClientID" Type="SalesTaxCode" />
      <Association Name="Client_ShopInventory" Member="ShopInventories" ThisKey="ContentEditsClientID" OtherKey="ClientID" Type="ShopInventory" />
      <Association Name="Client_Transaction" Member="Transactions" ThisKey="ContentEditsClientID" OtherKey="ClientID" Type="Transaction" />
      <Association Name="Client_webpages_Membership" Member="webpages_Memberships" ThisKey="ContentEditsClientID" OtherKey="ClientID" Type="webpages_Membership" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_UsersInRoles" Member="webpages_UsersInRoles">
    <Type Name="webpages_UsersInRole">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile_webpages_UsersInRole" Member="UserProfile" ThisKey="UserId" OtherKey="UserID" Type="UserProfile" IsForeignKey="true" />
      <Association Name="webpages_Role_webpages_UsersInRole" Member="webpages_Role" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Shops_ShopperID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Reported" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillingFirstName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BillingLastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BillingAddress1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BillingAddress2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BillingCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BillingState" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BillingZip" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BillingCountry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingFirstname" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ShippingLastName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ShippingAddress1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ShippingAddress2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ShippingCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingState" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShippingPostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingCountry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="AltContact" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="CustomerID" OtherKey="CustomerID" Type="Order" />
      <Association Name="Transaction_Customer" Member="Transaction" ThisKey="TransactionID" OtherKey="TransactionID" Type="Transaction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FailedOrders" Member="FailedOrders">
    <Type Name="FailedOrder">
      <Column Name="FailedOrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Imported" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Client_FailedOrder" Member="Client" ThisKey="ClientID" OtherKey="ContentEditsClientID" Type="Client" IsForeignKey="true" />
      <Association Name="Order_FailedOrder" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InventoryLinks" Member="InventoryLinks">
    <Type Name="InventoryLink">
      <Column Name="LinkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WebInventoryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="QBInventoryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Client_InventoryLink" Member="Client" ThisKey="ClientID" OtherKey="ContentEditsClientID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderLineItems" Member="OrderLineItems">
    <Type Name="OrderLineItem">
      <Column Name="LineItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InventoryName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FullDescription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PriceEach" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrderLineItem" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Reported" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResponseXML" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Receipt" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrderTax" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OrderShipping" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="AmountDiscount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PercentDiscount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OrderTaxPercentage" Type="System.Decimal" DbType="Decimal(6,3)" CanBeNull="true" />
      <Column Name="ShippingDescription" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RequestXML" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DiscountDescription" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Order_FailedOrder" Member="FailedOrders" ThisKey="OrderID" OtherKey="OrderID" Type="FailedOrder" />
      <Association Name="Order_OrderLineItem" Member="OrderLineItems" ThisKey="OrderID" OtherKey="OrderID" Type="OrderLineItem" />
      <Association Name="Client_Order" Member="Client" ThisKey="ClientID" OtherKey="ContentEditsClientID" Type="Client" IsForeignKey="true" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="Transaction_Order" Member="Transaction" ThisKey="TransactionID" OtherKey="TransactionID" Type="Transaction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuickbooksInventory" Member="QuickbooksInventories">
    <Type Name="QuickbooksInventory">
      <Column Name="QuickbooksInventoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ListID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QuickbooksInventory_ShopInventory" Member="ShopInventories" ThisKey="QuickbooksInventoryID" OtherKey="QuickbooksInventoryID" Type="ShopInventory" />
      <Association Name="QuickbooksInventory_ShopQuickbooksInventoryLink" Member="ShopQuickbooksInventoryLinks" ThisKey="QuickbooksInventoryID" OtherKey="QuickbooksInventoryID" Type="ShopQuickbooksInventoryLink" />
    </Type>
  </Table>
  <Table Name="dbo.ResponseXML" Member="ResponseXMLs">
    <Type Name="ResponseXML">
      <Column Name="ResponseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Guid" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Response" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Hresult" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Message" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Client_ResponseXML" Member="Client" ThisKey="ClientID" OtherKey="ContentEditsClientID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SalesTaxCodes" Member="SalesTaxCodes">
    <Type Name="SalesTaxCode">
      <Column Name="SalesTaxCodeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(8,4) NOT NULL" CanBeNull="false" />
      <Column Name="QuickbooksFullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Client_SalesTaxCode" Member="Client" ThisKey="ClientID" OtherKey="ContentEditsClientID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShopInventory" Member="ShopInventories">
    <Type Name="ShopInventory">
      <Column Name="InventoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuickbooksInventoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ShopInventory_ShopQuickbooksInventoryLink" Member="ShopQuickbooksInventoryLinks" ThisKey="InventoryID" OtherKey="ShopInventoryID" Type="ShopQuickbooksInventoryLink" />
      <Association Name="Client_ShopInventory" Member="Client" ThisKey="ClientID" OtherKey="ContentEditsClientID" Type="Client" IsForeignKey="true" />
      <Association Name="QuickbooksInventory_ShopInventory" Member="QuickbooksInventory" ThisKey="QuickbooksInventoryID" OtherKey="QuickbooksInventoryID" Type="QuickbooksInventory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShopQuickbooksInventoryLink" Member="ShopQuickbooksInventoryLinks">
    <Type Name="ShopQuickbooksInventoryLink">
      <Column Name="LinkID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShopInventoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuickbooksInventoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QuickbooksInventory_ShopQuickbooksInventoryLink" Member="QuickbooksInventory" ThisKey="QuickbooksInventoryID" OtherKey="QuickbooksInventoryID" Type="QuickbooksInventory" IsForeignKey="true" />
      <Association Name="ShopInventory_ShopQuickbooksInventoryLink" Member="ShopInventory" ThisKey="ShopInventoryID" OtherKey="InventoryID" Type="ShopInventory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.states" Member="states">
    <Type Name="state">
      <Column Name="abbr" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="canada" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="contiguous" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Guid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProcessedItemInventoryQuery" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProcessedItemSalesTaxQueryRs" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Transaction_Customer" Member="Customers" ThisKey="TransactionID" OtherKey="TransactionID" Type="Customer" />
      <Association Name="Transaction_Order" Member="Orders" ThisKey="TransactionID" OtherKey="TransactionID" Type="Order" />
      <Association Name="Client_Transaction" Member="Client" ThisKey="ClientID" OtherKey="ContentEditsClientID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(56) NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile_webpages_UsersInRole" Member="webpages_UsersInRoles" ThisKey="UserID" OtherKey="UserId" Type="webpages_UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Membership" Member="webpages_Memberships">
    <Type Name="webpages_Membership">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastPasswordFailureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordFailuresSinceLastSuccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordVerificationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PasswordVerificationTokenExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Client_webpages_Membership" Member="Client" ThisKey="ClientID" OtherKey="ContentEditsClientID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Roles" Member="webpages_Roles">
    <Type Name="webpages_Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="webpages_Role_webpages_UsersInRole" Member="webpages_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="webpages_UsersInRole" />
    </Type>
  </Table>
</Database>