//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickbooksWebService.developer.intuit.com {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://developer.intuit.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://developer.intuit.com/", ConfigurationName="developer.intuit.com.QBWebConnectorSvcSoap")]
    public interface QBWebConnectorSvcSoap {
        
        // CODEGEN: Generating message contract since element name strVersion from namespace http://developer.intuit.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/serverVersion", ReplyAction="*")]
        QuickbooksWebService.developer.intuit.com.serverVersionResponse serverVersion(QuickbooksWebService.developer.intuit.com.serverVersionRequest request);
        
        // CODEGEN: Generating message contract since element name strVersion from namespace http://developer.intuit.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/clientVersion", ReplyAction="*")]
        QuickbooksWebService.developer.intuit.com.clientVersionResponse clientVersion(QuickbooksWebService.developer.intuit.com.clientVersionRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://developer.intuit.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/authenticate", ReplyAction="*")]
        QuickbooksWebService.developer.intuit.com.authenticateResponse authenticate(QuickbooksWebService.developer.intuit.com.authenticateRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace http://developer.intuit.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/sendRequestXML", ReplyAction="*")]
        QuickbooksWebService.developer.intuit.com.sendRequestXMLResponse sendRequestXML(QuickbooksWebService.developer.intuit.com.sendRequestXMLRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace http://developer.intuit.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/receiveResponseXML", ReplyAction="*")]
        QuickbooksWebService.developer.intuit.com.receiveResponseXMLResponse receiveResponseXML(QuickbooksWebService.developer.intuit.com.receiveResponseXMLRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace http://developer.intuit.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/connectionError", ReplyAction="*")]
        QuickbooksWebService.developer.intuit.com.connectionErrorResponse connectionError(QuickbooksWebService.developer.intuit.com.connectionErrorRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace http://developer.intuit.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/getLastError", ReplyAction="*")]
        QuickbooksWebService.developer.intuit.com.getLastErrorResponse getLastError(QuickbooksWebService.developer.intuit.com.getLastErrorRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace http://developer.intuit.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/closeConnection", ReplyAction="*")]
        QuickbooksWebService.developer.intuit.com.closeConnectionResponse closeConnection(QuickbooksWebService.developer.intuit.com.closeConnectionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class serverVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="serverVersion", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.serverVersionRequestBody Body;
        
        public serverVersionRequest() {
        }
        
        public serverVersionRequest(QuickbooksWebService.developer.intuit.com.serverVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class serverVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strVersion;
        
        public serverVersionRequestBody() {
        }
        
        public serverVersionRequestBody(string strVersion) {
            this.strVersion = strVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class serverVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="serverVersionResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.serverVersionResponseBody Body;
        
        public serverVersionResponse() {
        }
        
        public serverVersionResponse(QuickbooksWebService.developer.intuit.com.serverVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class serverVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serverVersionResult;
        
        public serverVersionResponseBody() {
        }
        
        public serverVersionResponseBody(string serverVersionResult) {
            this.serverVersionResult = serverVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clientVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clientVersion", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.clientVersionRequestBody Body;
        
        public clientVersionRequest() {
        }
        
        public clientVersionRequest(QuickbooksWebService.developer.intuit.com.clientVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class clientVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strVersion;
        
        public clientVersionRequestBody() {
        }
        
        public clientVersionRequestBody(string strVersion) {
            this.strVersion = strVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clientVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clientVersionResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.clientVersionResponseBody Body;
        
        public clientVersionResponse() {
        }
        
        public clientVersionResponse(QuickbooksWebService.developer.intuit.com.clientVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class clientVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientVersionResult;
        
        public clientVersionResponseBody() {
        }
        
        public clientVersionResponseBody(string clientVersionResult) {
            this.clientVersionResult = clientVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticate", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.authenticateRequestBody Body;
        
        public authenticateRequest() {
        }
        
        public authenticateRequest(QuickbooksWebService.developer.intuit.com.authenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class authenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public authenticateRequestBody() {
        }
        
        public authenticateRequestBody(string strUserName, string strPassword) {
            this.strUserName = strUserName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticateResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.authenticateResponseBody Body;
        
        public authenticateResponse() {
        }
        
        public authenticateResponse(QuickbooksWebService.developer.intuit.com.authenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class authenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuickbooksWebService.developer.intuit.com.ArrayOfString authenticateResult;
        
        public authenticateResponseBody() {
        }
        
        public authenticateResponseBody(QuickbooksWebService.developer.intuit.com.ArrayOfString authenticateResult) {
            this.authenticateResult = authenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRequestXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRequestXML", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.sendRequestXMLRequestBody Body;
        
        public sendRequestXMLRequest() {
        }
        
        public sendRequestXMLRequest(QuickbooksWebService.developer.intuit.com.sendRequestXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class sendRequestXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strHCPResponse;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strCompanyFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string qbXMLCountry;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int qbXMLMajorVers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int qbXMLMinorVers;
        
        public sendRequestXMLRequestBody() {
        }
        
        public sendRequestXMLRequestBody(string ticket, string strHCPResponse, string strCompanyFileName, string qbXMLCountry, int qbXMLMajorVers, int qbXMLMinorVers) {
            this.ticket = ticket;
            this.strHCPResponse = strHCPResponse;
            this.strCompanyFileName = strCompanyFileName;
            this.qbXMLCountry = qbXMLCountry;
            this.qbXMLMajorVers = qbXMLMajorVers;
            this.qbXMLMinorVers = qbXMLMinorVers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRequestXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRequestXMLResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.sendRequestXMLResponseBody Body;
        
        public sendRequestXMLResponse() {
        }
        
        public sendRequestXMLResponse(QuickbooksWebService.developer.intuit.com.sendRequestXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class sendRequestXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendRequestXMLResult;
        
        public sendRequestXMLResponseBody() {
        }
        
        public sendRequestXMLResponseBody(string sendRequestXMLResult) {
            this.sendRequestXMLResult = sendRequestXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveResponseXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveResponseXML", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.receiveResponseXMLRequestBody Body;
        
        public receiveResponseXMLRequest() {
        }
        
        public receiveResponseXMLRequest(QuickbooksWebService.developer.intuit.com.receiveResponseXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class receiveResponseXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string response;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hresult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        public receiveResponseXMLRequestBody() {
        }
        
        public receiveResponseXMLRequestBody(string ticket, string response, string hresult, string message) {
            this.ticket = ticket;
            this.response = response;
            this.hresult = hresult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveResponseXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveResponseXMLResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.receiveResponseXMLResponseBody Body;
        
        public receiveResponseXMLResponse() {
        }
        
        public receiveResponseXMLResponse(QuickbooksWebService.developer.intuit.com.receiveResponseXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class receiveResponseXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int receiveResponseXMLResult;
        
        public receiveResponseXMLResponseBody() {
        }
        
        public receiveResponseXMLResponseBody(int receiveResponseXMLResult) {
            this.receiveResponseXMLResult = receiveResponseXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class connectionErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="connectionError", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.connectionErrorRequestBody Body;
        
        public connectionErrorRequest() {
        }
        
        public connectionErrorRequest(QuickbooksWebService.developer.intuit.com.connectionErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class connectionErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hresult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public connectionErrorRequestBody() {
        }
        
        public connectionErrorRequestBody(string ticket, string hresult, string message) {
            this.ticket = ticket;
            this.hresult = hresult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class connectionErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="connectionErrorResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.connectionErrorResponseBody Body;
        
        public connectionErrorResponse() {
        }
        
        public connectionErrorResponse(QuickbooksWebService.developer.intuit.com.connectionErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class connectionErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string connectionErrorResult;
        
        public connectionErrorResponseBody() {
        }
        
        public connectionErrorResponseBody(string connectionErrorResult) {
            this.connectionErrorResult = connectionErrorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastError", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.getLastErrorRequestBody Body;
        
        public getLastErrorRequest() {
        }
        
        public getLastErrorRequest(QuickbooksWebService.developer.intuit.com.getLastErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class getLastErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        public getLastErrorRequestBody() {
        }
        
        public getLastErrorRequestBody(string ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastErrorResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.getLastErrorResponseBody Body;
        
        public getLastErrorResponse() {
        }
        
        public getLastErrorResponse(QuickbooksWebService.developer.intuit.com.getLastErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class getLastErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getLastErrorResult;
        
        public getLastErrorResponseBody() {
        }
        
        public getLastErrorResponseBody(string getLastErrorResult) {
            this.getLastErrorResult = getLastErrorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConnectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConnection", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.closeConnectionRequestBody Body;
        
        public closeConnectionRequest() {
        }
        
        public closeConnectionRequest(QuickbooksWebService.developer.intuit.com.closeConnectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class closeConnectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        public closeConnectionRequestBody() {
        }
        
        public closeConnectionRequestBody(string ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConnectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConnectionResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QuickbooksWebService.developer.intuit.com.closeConnectionResponseBody Body;
        
        public closeConnectionResponse() {
        }
        
        public closeConnectionResponse(QuickbooksWebService.developer.intuit.com.closeConnectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class closeConnectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string closeConnectionResult;
        
        public closeConnectionResponseBody() {
        }
        
        public closeConnectionResponseBody(string closeConnectionResult) {
            this.closeConnectionResult = closeConnectionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QBWebConnectorSvcSoapChannel : QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QBWebConnectorSvcSoapClient : System.ServiceModel.ClientBase<QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap>, QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap {
        
        public QBWebConnectorSvcSoapClient() {
        }
        
        public QBWebConnectorSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QBWebConnectorSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QBWebConnectorSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QBWebConnectorSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickbooksWebService.developer.intuit.com.serverVersionResponse QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap.serverVersion(QuickbooksWebService.developer.intuit.com.serverVersionRequest request) {
            return base.Channel.serverVersion(request);
        }
        
        public string serverVersion(string strVersion) {
            QuickbooksWebService.developer.intuit.com.serverVersionRequest inValue = new QuickbooksWebService.developer.intuit.com.serverVersionRequest();
            inValue.Body = new QuickbooksWebService.developer.intuit.com.serverVersionRequestBody();
            inValue.Body.strVersion = strVersion;
            QuickbooksWebService.developer.intuit.com.serverVersionResponse retVal = ((QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap)(this)).serverVersion(inValue);
            return retVal.Body.serverVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickbooksWebService.developer.intuit.com.clientVersionResponse QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap.clientVersion(QuickbooksWebService.developer.intuit.com.clientVersionRequest request) {
            return base.Channel.clientVersion(request);
        }
        
        public string clientVersion(string strVersion) {
            QuickbooksWebService.developer.intuit.com.clientVersionRequest inValue = new QuickbooksWebService.developer.intuit.com.clientVersionRequest();
            inValue.Body = new QuickbooksWebService.developer.intuit.com.clientVersionRequestBody();
            inValue.Body.strVersion = strVersion;
            QuickbooksWebService.developer.intuit.com.clientVersionResponse retVal = ((QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap)(this)).clientVersion(inValue);
            return retVal.Body.clientVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickbooksWebService.developer.intuit.com.authenticateResponse QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap.authenticate(QuickbooksWebService.developer.intuit.com.authenticateRequest request) {
            return base.Channel.authenticate(request);
        }
        
        public QuickbooksWebService.developer.intuit.com.ArrayOfString authenticate(string strUserName, string strPassword) {
            QuickbooksWebService.developer.intuit.com.authenticateRequest inValue = new QuickbooksWebService.developer.intuit.com.authenticateRequest();
            inValue.Body = new QuickbooksWebService.developer.intuit.com.authenticateRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            QuickbooksWebService.developer.intuit.com.authenticateResponse retVal = ((QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap)(this)).authenticate(inValue);
            return retVal.Body.authenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickbooksWebService.developer.intuit.com.sendRequestXMLResponse QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap.sendRequestXML(QuickbooksWebService.developer.intuit.com.sendRequestXMLRequest request) {
            return base.Channel.sendRequestXML(request);
        }
        
        public string sendRequestXML(string ticket, string strHCPResponse, string strCompanyFileName, string qbXMLCountry, int qbXMLMajorVers, int qbXMLMinorVers) {
            QuickbooksWebService.developer.intuit.com.sendRequestXMLRequest inValue = new QuickbooksWebService.developer.intuit.com.sendRequestXMLRequest();
            inValue.Body = new QuickbooksWebService.developer.intuit.com.sendRequestXMLRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.strHCPResponse = strHCPResponse;
            inValue.Body.strCompanyFileName = strCompanyFileName;
            inValue.Body.qbXMLCountry = qbXMLCountry;
            inValue.Body.qbXMLMajorVers = qbXMLMajorVers;
            inValue.Body.qbXMLMinorVers = qbXMLMinorVers;
            QuickbooksWebService.developer.intuit.com.sendRequestXMLResponse retVal = ((QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap)(this)).sendRequestXML(inValue);
            return retVal.Body.sendRequestXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickbooksWebService.developer.intuit.com.receiveResponseXMLResponse QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap.receiveResponseXML(QuickbooksWebService.developer.intuit.com.receiveResponseXMLRequest request) {
            return base.Channel.receiveResponseXML(request);
        }
        
        public int receiveResponseXML(string ticket, string response, string hresult, string message) {
            QuickbooksWebService.developer.intuit.com.receiveResponseXMLRequest inValue = new QuickbooksWebService.developer.intuit.com.receiveResponseXMLRequest();
            inValue.Body = new QuickbooksWebService.developer.intuit.com.receiveResponseXMLRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.response = response;
            inValue.Body.hresult = hresult;
            inValue.Body.message = message;
            QuickbooksWebService.developer.intuit.com.receiveResponseXMLResponse retVal = ((QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap)(this)).receiveResponseXML(inValue);
            return retVal.Body.receiveResponseXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickbooksWebService.developer.intuit.com.connectionErrorResponse QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap.connectionError(QuickbooksWebService.developer.intuit.com.connectionErrorRequest request) {
            return base.Channel.connectionError(request);
        }
        
        public string connectionError(string ticket, string hresult, string message) {
            QuickbooksWebService.developer.intuit.com.connectionErrorRequest inValue = new QuickbooksWebService.developer.intuit.com.connectionErrorRequest();
            inValue.Body = new QuickbooksWebService.developer.intuit.com.connectionErrorRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.hresult = hresult;
            inValue.Body.message = message;
            QuickbooksWebService.developer.intuit.com.connectionErrorResponse retVal = ((QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap)(this)).connectionError(inValue);
            return retVal.Body.connectionErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickbooksWebService.developer.intuit.com.getLastErrorResponse QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap.getLastError(QuickbooksWebService.developer.intuit.com.getLastErrorRequest request) {
            return base.Channel.getLastError(request);
        }
        
        public string getLastError(string ticket) {
            QuickbooksWebService.developer.intuit.com.getLastErrorRequest inValue = new QuickbooksWebService.developer.intuit.com.getLastErrorRequest();
            inValue.Body = new QuickbooksWebService.developer.intuit.com.getLastErrorRequestBody();
            inValue.Body.ticket = ticket;
            QuickbooksWebService.developer.intuit.com.getLastErrorResponse retVal = ((QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap)(this)).getLastError(inValue);
            return retVal.Body.getLastErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuickbooksWebService.developer.intuit.com.closeConnectionResponse QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap.closeConnection(QuickbooksWebService.developer.intuit.com.closeConnectionRequest request) {
            return base.Channel.closeConnection(request);
        }
        
        public string closeConnection(string ticket) {
            QuickbooksWebService.developer.intuit.com.closeConnectionRequest inValue = new QuickbooksWebService.developer.intuit.com.closeConnectionRequest();
            inValue.Body = new QuickbooksWebService.developer.intuit.com.closeConnectionRequestBody();
            inValue.Body.ticket = ticket;
            QuickbooksWebService.developer.intuit.com.closeConnectionResponse retVal = ((QuickbooksWebService.developer.intuit.com.QBWebConnectorSvcSoap)(this)).closeConnection(inValue);
            return retVal.Body.closeConnectionResult;
        }
    }
}
